//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINO
    {
        public int IDDESTINO { get; set; }
        public string PAIS { get; set; }
        public string CIUDAD { get; set; }
        public int IMPUESTO { get; set; }
    }
}
