//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeguimientoPaquetesEntities : DbContext
    {
        public SeguimientoPaquetesEntities()
            : base("name=SeguimientoPaquetesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DESTINO> DESTINOes { get; set; }
        public DbSet<ENVIO> ENVIOs { get; set; }
        public DbSet<ESTADO> ESTADOes { get; set; }
        public DbSet<ORIGEN> ORIGENs { get; set; }
        public DbSet<PAGO> PAGOes { get; set; }
        public DbSet<PEDIDOS> PEDIDOS { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
