//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        public int IDPEDIDO { get; set; }
        public int IDUSUARIO { get; set; }
        public int IDORIGEN { get; set; }
        public int IDDESTINO { get; set; }
        public int IDPAGO { get; set; }
        public int IDENVIO { get; set; }
        public int IDESTADO { get; set; }
        public int TOTAL { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual DESTINO DESTINO { get; set; }
        public virtual ENVIO ENVIO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual ORIGEN ORIGEN { get; set; }
        public virtual PAGO PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
