//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        public int IDPEDIDO { get; set; }
        public int IDUSUARIO { get; set; }
        public string IDPAISORIGEN { get; set; }
        public string IDPAISDESTINO { get; set; }
        public string IDPAGO { get; set; }
        public string IDENVIO { get; set; }
        public string IDESTADO { get; set; }
        public int TOTAL { get; set; }
        public string DESCRIPCION { get; set; }
        public string IDCIUDADDESTINO { get; set; }
        public string IDCIUDADORIGEN { get; set; }
    }
}
