//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int IDUSUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string ALIAS { get; set; }
        public string PASS { get; set; }
        public string TIPO_USUARIO { get; set; }
        public string ESTADO_USUARIO { get; set; }
    }
}
